[project]
name = "yahoofinance"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "cerberus>=1.3.7",
    "pyyaml>=6.0.2",
    "requests>=2.32.3",
    "yfinance>=0.2.61",
    "sc-utility>=1.0.2",    
]
